const songs: { id: number; singer: string; song: string }[] = [
  { id: 1, singer: "John Melody", song: "Echoes of the Night" },
  { id: 2, singer: "Sarah Harmony", song: "Whispering Winds" },
  { id: 3, singer: "Mike Thunder", song: "Rock the Stars" },
  { id: 4, singer: "Lena Dreamer", song: "Moonlight Serenade" },
  { id: 5, singer: "Jake Rhythm", song: "Dancing Through Time" },
  { id: 6, singer: "Olivia Sky", song: "Endless Horizon" },
  { id: 7, singer: "Tommy Beats", song: "Neon City Lights" },
  { id: 8, singer: "Emma Soul", song: "Heartbeat Symphony" },
  { id: 9, singer: "David Echo", song: "Lost in the Sound" },
  { id: 10, singer: "Nina Vibes", song: "Golden Waves" },
  { id: 11, singer: "Leo Striker", song: "Firestorm" },
  { id: 12, singer: "Hannah Whisper", song: "Softly Falling" },
  { id: 13, singer: "Carlos Star", song: "Burning Bright" },
  { id: 14, singer: "Sophie Muse", song: "Timeless Love" },
  { id: 15, singer: "Zack Pulse", song: "Electric Dreams" },
  { id: 16, singer: "Mia Serenade", song: "Fading Memories" },
  { id: 17, singer: "Danny Moon", song: "Lunar Groove" },
  { id: 18, singer: "Chloe Ocean", song: "Deep Blue Melody" },
  { id: 19, singer: "Ethan Wild", song: "Run Free" },
  { id: 20, singer: "Bella Harmony", song: "Song of the Sky" },
  { id: 21, singer: "Mark Blaze", song: "City Sparks" },
  { id: 22, singer: "Ella Sway", song: "Dancing Alone" },
  { id: 23, singer: "Nathan Storm", song: "Thunder Roads" },
  { id: 24, singer: "Julia Dream", song: "Floating Away" },
  { id: 25, singer: "Lucas Beat", song: "Pulse of the City" },
  { id: 26, singer: "Amber Star", song: "Shining On" },
  { id: 27, singer: "Sam Echo", song: "Lost Frequencies" },
  { id: 28, singer: "Diana Glow", song: "Starlit Nights" },
  { id: 29, singer: "Tyler Wave", song: "Crashing Tides" },
  { id: 30, singer: "Sienna Bloom", song: "Spring Awakens" },
  { id: 31, singer: "Felix Riff", song: "Guitar Serenade" },
  { id: 32, singer: "Holly Breeze", song: "Windchime Wishes" },
  { id: 33, singer: "Brandon Flame", song: "Inferno Sound" },
  { id: 34, singer: "Claire Luna", song: "Midnight Ballad" },
  { id: 35, singer: "Derek Chill", song: "Laid-back Vibes" },
  { id: 36, singer: "Violet Nova", song: "Supernova Love" },
  { id: 37, singer: "Ryan Sparks", song: "Ignite the Night" },
  { id: 38, singer: "Natalie Whisper", song: "Soft as Snow" },
  { id: 39, singer: "Jasper Wave", song: "Drifting Away" },
  { id: 40, singer: "Madison Sky", song: "Cloud Nine" },
  { id: 41, singer: "Liam Verse", song: "Lyric Dreams" },
  { id: 42, singer: "Tessa Glow", song: "Neon Sunset" },
  { id: 43, singer: "Adrian Shadow", song: "Echoes in the Dark" },
  { id: 44, singer: "Zoey Tempo", song: "Fast Lane Love" },
  { id: 45, singer: "Evan Rhapsody", song: "Melodic Journey" },
  { id: 46, singer: "Sophia Rain", song: "Falling Drops" },
  { id: 47, singer: "Julian Star", song: "Celestial Rhythm" },
  { id: 48, singer: "Paige Ocean", song: "Waves of Time" },
  { id: 49, singer: "Max Thunder", song: "Lightning Strikes" },
  { id: 50, singer: "Lily Serenade", song: "Golden Hour" },
  { id: 51, singer: "Henry Flash", song: "Speed of Sound" },
  { id: 52, singer: "Carla Vibe", song: "Feel the Beat" },
  { id: 53, singer: "Oscar Echo", song: "Silent No More" },
  { id: 54, singer: "Megan Rhythm", song: "Bassline Love" },
  { id: 55, singer: "Cody Blaze", song: "Turn Up the Heat" },
  { id: 56, singer: "Isla Moon", song: "Starry Eyes" },
  { id: 57, singer: "Riley Storm", song: "Wild Winds" },
  { id: 58, singer: "Faith Muse", song: "Sing to Me" },
  { id: 59, singer: "Zane Rocker", song: "Guitar Hero" },
  { id: 60, singer: "Elena Blue", song: "Cool Water" },
  { id: 61, singer: "Vincent Beat", song: "March to the Drums" },
  { id: 62, singer: "Carmen Sway", song: "Love in Motion" },
  { id: 63, singer: "Troy Sky", song: "Soaring High" },
  { id: 64, singer: "Layla Echo", song: "Shattered Sounds" },
  { id: 65, singer: "Elliot Nova", song: "Cosmic Energy" },
  { id: 66, singer: "Brooke Harmony", song: "Calm Within" },
  { id: 67, singer: "Hudson Chill", song: "Slow and Steady" },
  { id: 68, singer: "Natalia Rush", song: "Speed of Light" },
  { id: 69, singer: "Jace Phoenix", song: "Rising Again" },
  { id: 70, singer: "Lana Serenity", song: "Dream Away" },
  { id: 71, singer: "Damien Sound", song: "Echoing Silence" },
  { id: 72, singer: "Ava Starling", song: "Bright as Fire" },
  { id: 73, singer: "Tristan Bass", song: "Funk Fever" },
  { id: 74, singer: "Genevieve Snow", song: "Cold Kiss" },
  { id: 75, singer: "Connor Blaze", song: "Fire and Ice" },
  { id: 76, singer: "Melody Finch", song: "Singing Free" },
  { id: 77, singer: "Theo Orbit", song: "Spinning Around" },
  { id: 78, singer: "Vivian Storm", song: "Weather the Night" },
  { id: 79, singer: "Ezra Chord", song: "Perfect Harmony" },
  { id: 80, singer: "Autumn Sky", song: "Changing Colors" },
  { id: 81, singer: "Finn Horizon", song: "Endless Roads" },
  { id: 82, singer: "Beatrice Glow", song: "Shining for You" },
  { id: 83, singer: "Weston Pulse", song: "Heartbeat Rhythm" },
  { id: 84, singer: "Daphne Song", song: "Melody of Us" },
  { id: 85, singer: "Spencer Thunder", song: "Electric Storm" },
  { id: 86, singer: "Serena Wave", song: "Tidal Love" },
  { id: 87, singer: "Axel Riff", song: "Shredding It Up" },
  { id: 88, singer: "Celeste Rain", song: "Gentle Drizzle" },
  { id: 89, singer: "Lincoln Rock", song: "Solid as Stone" },
  { id: 90, singer: "Delilah Charm", song: "Sweetest Sound" },
  { id: 91, singer: "Orion Sparks", song: "Galactic Tune" },
  { id: 92, singer: "Giselle Breeze", song: "Soft as Air" },
  { id: 93, singer: "Maverick Moon", song: "Night Rider" },
  { id: 94, singer: "Camille Lush", song: "Velvet Symphony" },
  { id: 95, singer: "Jonas Echo", song: "Fading Out" },
  { id: 96, singer: "Kendall Star", song: "Glow Up" },
  { id: 97, singer: "Ronan Tempest", song: "Storm Chaser" },
  { id: 98, singer: "Lacey Rhythm", song: "Love on Repeat" },
  { id: 99, singer: "Xander Frost", song: "Cold Touch" },
  { id: 100, singer: "Zelda Nova", song: "Falling Star" },
];

export default songs;
