const songs: { singer: string; song: string }[] = [
  { singer: "John Melody", song: "Echoes of the Night" },
  { singer: "Sarah Harmony", song: "Whispering Winds" },
  { singer: "Mike Thunder", song: "Rock the Stars" },
  { singer: "Lena Dreamer", song: "Moonlight Serenade" },
  { singer: "Jake Rhythm", song: "Dancing Through Time" },
  { singer: "Olivia Sky", song: "Endless Horizon" },
  { singer: "Tommy Beats", song: "Neon City Lights" },
  { singer: "Emma Soul", song: "Heartbeat Symphony" },
  { singer: "David Echo", song: "Lost in the Sound" },
  { singer: "Nina Vibes", song: "Golden Waves" },
  { singer: "Leo Striker", song: "Firestorm" },
  { singer: "Hannah Whisper", song: "Softly Falling" },
  { singer: "Carlos Star", song: "Burning Bright" },
  { singer: "Sophie Muse", song: "Timeless Love" },
  { singer: "Zack Pulse", song: "Electric Dreams" },
  { singer: "Mia Serenade", song: "Fading Memories" },
  { singer: "Danny Moon", song: "Lunar Groove" },
  { singer: "Chloe Ocean", song: "Deep Blue Melody" },
  { singer: "Ethan Wild", song: "Run Free" },
  { singer: "Bella Harmony", song: "Song of the Sky" },
  { singer: "Mark Blaze", song: "City Sparks" },
  { singer: "Ella Sway", song: "Dancing Alone" },
  { singer: "Nathan Storm", song: "Thunder Roads" },
  { singer: "Julia Dream", song: "Floating Away" },
  { singer: "Lucas Beat", song: "Pulse of the City" },
  { singer: "Amber Star", song: "Shining On" },
  { singer: "Sam Echo", song: "Lost Frequencies" },
  { singer: "Diana Glow", song: "Starlit Nights" },
  { singer: "Tyler Wave", song: "Crashing Tides" },
  { singer: "Sienna Bloom", song: "Spring Awakens" },
  { singer: "Felix Riff", song: "Guitar Serenade" },
  { singer: "Holly Breeze", song: "Windchime Wishes" },
  { singer: "Brandon Flame", song: "Inferno Sound" },
  { singer: "Claire Luna", song: "Midnight Ballad" },
  { singer: "Derek Chill", song: "Laid-back Vibes" },
  { singer: "Violet Nova", song: "Supernova Love" },
  { singer: "Ryan Sparks", song: "Ignite the Night" },
  { singer: "Natalie Whisper", song: "Soft as Snow" },
  { singer: "Jasper Wave", song: "Drifting Away" },
  { singer: "Madison Sky", song: "Cloud Nine" },
  { singer: "Liam Verse", song: "Lyric Dreams" },
  { singer: "Tessa Glow", song: "Neon Sunset" },
  { singer: "Adrian Shadow", song: "Echoes in the Dark" },
  { singer: "Zoey Tempo", song: "Fast Lane Love" },
  { singer: "Evan Rhapsody", song: "Melodic Journey" },
  { singer: "Sophia Rain", song: "Falling Drops" },
  { singer: "Julian Star", song: "Celestial Rhythm" },
  { singer: "Paige Ocean", song: "Waves of Time" },
  { singer: "Max Thunder", song: "Lightning Strikes" },
  { singer: "Lily Serenade", song: "Golden Hour" },
  { singer: "Henry Flash", song: "Speed of Sound" },
  { singer: "Carla Vibe", song: "Feel the Beat" },
  { singer: "Oscar Echo", song: "Silent No More" },
  { singer: "Megan Rhythm", song: "Bassline Love" },
  { singer: "Cody Blaze", song: "Turn Up the Heat" },
  { singer: "Isla Moon", song: "Starry Eyes" },
  { singer: "Riley Storm", song: "Wild Winds" },
  { singer: "Faith Muse", song: "Sing to Me" },
  { singer: "Zane Rocker", song: "Guitar Hero" },
  { singer: "Elena Blue", song: "Cool Water" },
  { singer: "Vincent Beat", song: "March to the Drums" },
  { singer: "Carmen Sway", song: "Love in Motion" },
  { singer: "Troy Sky", song: "Soaring High" },
  { singer: "Layla Echo", song: "Shattered Sounds" },
  { singer: "Elliot Nova", song: "Cosmic Energy" },
  { singer: "Brooke Harmony", song: "Calm Within" },
  { singer: "Hudson Chill", song: "Slow and Steady" },
  { singer: "Natalia Rush", song: "Speed of Light" },
  { singer: "Jace Phoenix", song: "Rising Again" },
  { singer: "Lana Serenity", song: "Dream Away" },
  { singer: "Damien Sound", song: "Echoing Silence" },
  { singer: "Ava Starling", song: "Bright as Fire" },
  { singer: "Tristan Bass", song: "Funk Fever" },
  { singer: "Genevieve Snow", song: "Cold Kiss" },
  { singer: "Connor Blaze", song: "Fire and Ice" },
  { singer: "Melody Finch", song: "Singing Free" },
  { singer: "Theo Orbit", song: "Spinning Around" },
  { singer: "Vivian Storm", song: "Weather the Night" },
  { singer: "Ezra Chord", song: "Perfect Harmony" },
  { singer: "Autumn Sky", song: "Changing Colors" },
  { singer: "Finn Horizon", song: "Endless Roads" },
  { singer: "Beatrice Glow", song: "Shining for You" },
  { singer: "Weston Pulse", song: "Heartbeat Rhythm" },
  { singer: "Daphne Song", song: "Melody of Us" },
  { singer: "Spencer Thunder", song: "Electric Storm" },
  { singer: "Serena Wave", song: "Tidal Love" },
  { singer: "Axel Riff", song: "Shredding It Up" },
  { singer: "Celeste Rain", song: "Gentle Drizzle" },
  { singer: "Lincoln Rock", song: "Solid as Stone" },
  { singer: "Delilah Charm", song: "Sweetest Sound" },
  { singer: "Orion Sparks", song: "Galactic Tune" },
  { singer: "Giselle Breeze", song: "Soft as Air" },
  { singer: "Maverick Moon", song: "Night Rider" },
  { singer: "Camille Lush", song: "Velvet Symphony" },
  { singer: "Jonas Echo", song: "Fading Out" },
  { singer: "Kendall Star", song: "Glow Up" },
  { singer: "Ronan Tempest", song: "Storm Chaser" },
  { singer: "Lacey Rhythm", song: "Love on Repeat" },
  { singer: "Xander Frost", song: "Cold Touch" },
  { singer: "Zelda Nova", song: "Falling Star" },
];

export default songs;
